### PR TITLE
Reports/fix zoom behavior

### LINKED ISSUE #611: UX flaws in viewing the details of a clustered report/planning in Aachen's report map
# What is the problem?

If I open a planning via deep-link
(e.g. https://radbuegel-aachen.de/meldungen/karte/1838),
I cannot spot the requested feature on the map.
The map item is part of a cluster, so I cannot spot the single geometry.
Even if I zoom in, the feature is not highlighted, it just looks like "all other features".

The same problem applies if I click on another feature that is part of a cluster

GIF 30 10 2020 20-12-59

# What is the expected result?

* if I use a deep-link
  * the map will zoom in until no map items are clustered
  * the inspected feature is emphasized, e.g. by making it bigger or adding some sort of halo to it.

# Background
Sumbled upon this while working at https://github.com/FixMyBerlin/fixmy.frontend/issues/568

### PR DESCRIPTION
**Pull request by cafca**
This is an attempt to fix some of the zoom behavior in the reports app. 

- Map doesn't zoom out anymore when opening a detail panel from a zoom point that's further in than the standard zoom for the detail view
- Map shifts to an offset so that currently selected report is in the middle of the map view even when the detail panel is open
- The position of the "add new report" / "more info" button on the overview map was fixed to be in the center of the viewport and animate on opening/closing the detail panel
- The preview image in the map popup was restored, it was invisible because it was set as the background image on an anchor element without further content.

**There's a still to be resolved issue where sometimes markers and marker clusters are visible for the same reports. I haven't been able to track that down yet.**

Fixes #611

## How Has This Been Tested?

- Navigate to overview map, observe map zoom level and marker position when opening detail pane
- Open map using deep link, observe the same

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by s-pic** [comment]
Before I do any functional tests:
1. Code looks solid, good job @cafca .
2. When I checkout the branch and do a fresh install, I see 
   a) _a lot_ of eslint warnings 
```
propType "someProp" is not required, but has no corresponding defaultProps declaration
```
I know that is out of scope of the MR, but we should weaken that rule soon OR fix those lines.
  b) the following errors
````
ERROR in ./node_modules/@mapbox/mapbox-gl-draw/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:\dev\fmbtmp\node_modules\@mapbox\mapbox-gl-draw\index.js: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.

> 1 | import runSetup from './src/setup';
    | ^
  2 | import setupOptions from './src/options';
  3 | import setupAPI from './src/api';
  4 | import * as Constants from './src/constants';
    at Object._raise (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:790:17)
    at Object.raiseWithData (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:783:17)
    at Object.assertModuleNodeAllowed (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:11781:12)
    at Object.parseStatementContent (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:11752:16)
    at Object.parseStatement (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:11639:17)
    at Object.parseBlockOrModuleBlockBody (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:12221:25)
    at Object.parseBlockBody (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:12207:10)
    at Object.parseTopLevel (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:11570:10)
    at Object.parse (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:13381:10)
    at parse (D:\dev\fmbtmp\node_modules\@babel\parser\lib\index.js:13434:38)
    at parser (D:\dev\fmbtmp\node_modules\@babel\core\lib\parser\index.js:54:34)
    at parser.next (<anonymous>)
    at normalizeFile (D:\dev\fmbtmp\node_modules\@babel\core\lib\transformation\normalize-file.js:99:38)
    at normalizeFile.next (<anonymous>)
    at run (D:\dev\fmbtmp\node_modules\@babel\core\lib\transformation\index.js:31:50)
    at run.next (<anonymous>)

ERROR in D:\dev\fmbtmp\src\apps\Spielstrassen\pages\Register.tsx
./src/apps/Spielstrassen/pages/Register.tsx
[tsl] ERROR in D:\dev\fmbtmp\src\apps\Spielstrassen\pages\Register.tsx(131,23)
      TS2322: Type '{ street: string; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<RouteComponentProps<any, StaticContext, unknown>, never> | (Pick<RouteComponentProps<any, StaticCon
text, unknown>, never> & { ...; }), any, any>> & Readonly<...> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>)'.
  Property 'street' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<RouteComponentProps<any, StaticContext, unknown>, never> | (Pick<RouteComponentProps<any, StaticContext, unknown>, never> &
 { ...; }), any, any>> & Readonly<...> & Readonly<...>) | (IntrinsicAttributes & ... 2 more ... & Readonly<...>)'.
i ｢wdm｣: Failed to compile.

```
I will try to fix them myself and commit directly -- hoping that this works for you.

**Comment by s-pic** [comment]
✔️ functional tests OK

File: src/pages/Reports/pages/OverviewMap/components/CTAButton.js [hunk 1]
```diff
@@ -4,12 +4,22 @@ import PropTypes from 'prop-types';
...
   left: 0;
-  right: 0;
-  margin: ${(props) => (props.shiftLeft ? '0 auto 0 15%' : 'auto')};
+  width: 100%;
+  height: 100%;
+  display: flex;
+  justify-content: center;
+  align-items: flex-end;
+  padding-bottom: 50px;
+  padding-right: ${(props) => (props.shiftLeft ? '400px' : '0')};
```
Comment (s-pic) [inline src/pages/Reports/pages/OverviewMap/components/CTAButton.js:17]: minor thing: I stumbled upon this and remembered that -- in order to achieve smooth animations - one should to use
rather use `translate` as `transition-property` than animating things like `padding` and `margin`
> The most effective way to avoid excess work for your CPU is to animate low-cost properties that only affect compositing - those being transform and opacity
https://www.netcentric.biz/insights/2017/09/css-transition-performance.html

I played a bit around, also hoping to reduce complexity by getting rid of the `ButtonWrapper`, but I started to see difficulties which -- I assume -- lead you to this implementation.

So I am good with it ;)

File: src/pages/Reports/pages/OverviewMap/components/WebglMap.js [hunk 2]
```diff
@@ -46,23 +48,40 @@ class WebglMap extends PureComponent {
...
+    const zoomTarget = config.reports.overviewMap.zoomDeepLinkedMarkers || 16;
 
     if (center) {
       const newCameraOptions = { center };
-      if (zoomIn) {
-        newCameraOptions.zoom =
-          config.reports.overviewMap.zoomDeepLinkedMarkers || 16;
+      if (isCTAButtonShifted) newCameraOptions.padding = { right: 400 };
+      if (zoomIn && this.map.getZoom() < zoomTarget) {
+        newCameraOptions.zoom = zoomTarget;
```
Comment (s-pic) [inline src/pages/Reports/pages/OverviewMap/components/WebglMap.js:65]: I would like to see some comments here.
Besides that: nice and clean code 👍

File: src/services/api/errors.ts [hunk 3]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable max-classes-per-file */
```
Comment (s-pic) [inline src/services/api/errors.ts:1]: We should create a cleanup issue/epic regarding eslint.

**Review by s-pic — APPROVED** [review]
[1 little thing](https://github.com/FixMyBerlin/fixmy.frontend/pull/646/files#r522398676), besides that: 👍

File: src/pages/Reports/pages/OverviewMap/components/CTAButton.js (hunk 1 above)
Comment (cafca) [reply src/pages/Reports/pages/OverviewMap/components/CTAButton.js:17]: That's super interesting and I didn't know about it, thank you. So I take it that using `translate` didn't work when you tried it? I would really like to keep a watch out for performance issues in the reports app.

File: src/pages/Reports/pages/OverviewMap/components/WebglMap.js (hunk 2 above)
Comment (cafca) [reply src/pages/Reports/pages/OverviewMap/components/WebglMap.js:65]: You are right, I will add some.

File: src/services/api/errors.ts (hunk 3 above)
Comment (cafca) [reply src/services/api/errors.ts:1]: I made an issue for this specifically but yes, I would like to do that in December.

**Comment by cafca** [comment]
@s-pic Regarding the build and linter errors you mentioned above - I don't see them on my side and they would also turn up in the linter Github action. Maybe it's something with your dev environment? Let me know if i can help. Sometimes I had problems when my IDE was configured with some global rules that bled into a project setup but I don't know if that can happen in your case.

File: src/services/api/errors.ts (hunk 3 above)
Comment (cafca) [reply src/services/api/errors.ts:1]: https://github.com/FixMyBerlin/fixmy.frontend/issues/645

File: src/pages/Reports/pages/OverviewMap/components/CTAButton.js (hunk 1 above)
Comment (cafca) [reply src/pages/Reports/pages/OverviewMap/components/CTAButton.js]: Works for me!

**Comment by cafca** [comment]
I removed `fitExtentOnPopupClose` because it was permanently disabled and I would really like to reduce complexity in the reports app.
